package main

var routes = Routes{
    Route{
        "Index",
        "POST",
        "/",
        Index,
    },
    Route{
        "Index",
        "GET",
        "/",
        Index,
    },
    Route{
        "Index",
        "PUT",
        "/",
        Index,
    },
    Route{
        "Index",
        "DELETE",
        "/",
        Index,
    },
    Route{
        "PostObjects",
        "POST",
        "/objects/{name}",
        PostObjects,
    },
    Route{
        "GetObjects",
        "GET",
        "/objects/{name}",
        GetObjects,
    },
    Route{
        "GetObjectsById",
        "GET",
        "/objects/{name}/{id}",
        GetObjectsById,
    },
    Route{
        "PutObjectsById",
        "PUT",
        "/objects/{name}/{id}",
        PutObjectsById,
    },
    Route{
        "DeleteObjectsById",
        "DELETE",
        "/objects/{name}/{id}",
        DeleteObjectsById,
    },

}